[build]
  command = "npx nx build web"
  publish = "dist/apps/web/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://tomlist.onrender.com"
  status = 200
  force = true
